spring:

  profiles:
    active: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/database/querydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver




  output:
    ansi:
      enabled: always

logging:
  level:
    org:
      hibernate:
        SQL: debug
