management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true # info.app 프로퍼티
  endpoint:
    health:
      show-components: always
    shutdown:
      enabled: true # shutdown 기본으로 활성되지 않음. 실행 시 앱 종료
  endpoints:
    web:
      exposure:
        include: "*" # 모든 엔드포인트를 웹에 노출


info:
  app:
    name: hello-actuator
    company: yh

