spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL  # MySQL ??? H2 ??
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    open-in-view: false
#    database-platform: org.hibernate.dialect.MySQL8Dialect  # MySQL8 Dialect ??
#    show-sql: true
    hibernate:
      ddl-auto: create  # ?? update
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.MySQL8Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

  output:
    ansi:
      enabled: always

logging:
  level:
    org.hibernate.SQL: debug  # SQL ?? ?? ??
    org.hibernate.orm.jdbc.bind: trace  # ??? ???? ??